
@host = http://localhost:8080
@owner = raghav_dev

POST {{host}}/pods
Content-Type: application/json

{
  "name": "Physics Notes",
  "ownerUserId": "{{owner}}"
}

> {%

    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.global.set("pod_id", response.body.podId);
    client.log("Captured Pod ID: " + client.global.get("pod_id"));
%}

###


POST {{host}}/pods/{{pod_id}}/data
Content-Type: application/json

{
  "content": "Newton's second law states that Force equals mass times acceleration (F=ma). It implies that force is the rate of change of momentum."
}

###

POST {{host}}/pods/{{pod_id}}/data
Content-Type: application/json

{
  "content": "Quantum mechanics differs from classical physics. It deals with probabilities rather than certainties. Schrödinger's cat is a famous thought experiment."
}

###


POST {{host}}/indexing/pods/{{pod_id}}

> {%
    client.global.set("job_id", response.body.jobId);
%}

###

#This must complete for further usage
GET {{host}}/indexing/jobs/{{job_id}}

> {%
    client.test("Job Status Check", function() {
        var status = response.body.status;
        client.log("Current Status: " + status);
        if (status === "RUNNING" || status === "PENDING") {
            client.log(">>> CLICK RUN AGAIN - Job is still processing...");
        } else if (status === "FAILED") {
            client.log("ERROR: " + response.body.errorMessage);
        }
    });
%}

###


#Query the Intelligence Engine (RAG)
POST {{host}}/pods/{{pod_id}}/query
Content-Type: application/json

{
  "question": "Difference between Newtonian and quantum mechanics"
}

###


#View Metrics (Actuator)
GET {{host}}/actuator/metrics/datahub.indexing.jobs.completed